version: '3.8'

services:
  backend:
    image: employee_manager:latest
    build:
      context: .
    ports:
      - "9000:8080"
    env_file:
      - .env
    networks:
      - localnet
    depends_on:
      appdb:
        condition: service_healthy
  appdb:
    image: mysql:8.4.0

    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
      - MYSQL_DATABASE=supportportal
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 5s
      timeout: 20s
      interval: 5s
      retries: 10
    ports:
      - "3307:3306"
    networks:
      - localnet


networks:
  localnet:
    driver: bridge
